repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: forbid-new-submodules
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
#      - id: check-yaml

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        description: Checks for common misspellings.
        types_or: [python, rst, markdown]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
        name: pycln (Python unused imports)

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [
            --line-length=100,
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
            --combine-as,
            --line-length=100,
            --ensure-newline-before-comments,
            --force-single-line-imports,
            --single-line-exclusions=typing,
            --trailing-comma,
            --multi-line=3,
            --lines-after-imports=2,
            --use-parentheses,
        ]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies:
          - flake8-2020
          - flake8-bandit
          - flake8-bugbear
          - flake8-coding
          - flake8-comprehensions
          - flake8-debugger
          - flake8-deprecated
#          - flake8-docstrings
          - flake8-pep3101
          - flake8-string-format
#          - flake8-rst-docstrings
#          - flake8-typing-imports
#          - pep8-naming
        types: [python]
        args: [
            --max-complexity=10,
            --max-line-length=150,
            --statistics,
            --ignore=C101 RST210 S101 W503,
            --per-file-ignores=
                tests/*.py:D103
                oups/__init__.py:F401
                oups/chainagg.py:C901
                oups/jcumsegagg.py:C901
                oups/writer.py:C901
                oups/cumsegagg.py:C901
                oups/segmentby.py:S001
                oups/segmentby.py:C901
        ]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        files: ^oups/
        additional_dependencies:
          - toml

# flake8 ignore justifications
# ----------------------------
# C901: Function is too complex
# D103: Missing docstring in public function
# RST210: Inline strong start-string without end-string (when describing **kwargs parameter)
# S101: Use of assert detected (use of assert normal for pytest)
# W503: Line break before binary operator
