[tool.poetry]
name = "oups"
version = "0.1.0"
description = "Collection of parquet datasets."
authors = ["Yohplala"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
fastparquet = {git = "https://github.com/yohplala/fastparquet.git", rev = "cmidx_write_rg"}
vaex = "^4.6.0"
pandas = "^1.3.4"

[tool.poetry.dev-dependencies]
"black" = "^21.12b0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
