[tool.poetry]
name = "oups"
version = "0.1.0"
description = "Collection of parquet datasets."
authors = ["Yohplala"]
license = "Apache-2.0"
repository = "https://github.com/yohplala/oups"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
sortedcontainers = "^2.1.0"
llvmlite = "^0.37.0" # no wheel for python 3.9 if below.
pandas = "^1.3.4"
fastparquet = {git = "https://github.com/yohplala/fastparquet.git", rev = "cmidx_write_rg"}
vaex = "^4.6.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
pytest = "^6.2.5"

[build-system]
requires = [
    "setuptools",
    "poetry-core>=1.0.7"
]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
