name: docs

# Build and deploy oups API documentation.

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install build dependencies
      - name: Install build dependencies
        run: python -m pip install --upgrade pip setuptools wheel poetry pre-commit

      # Install extra docs dependencies
      - name: Install extra docs dependencies
        run: pip install numpydoc sphinx sphinx-rtd-theme

      # Build docs
      - name: Build docs
        run: catchsegv sphinx-build docs/source docs/build

      # Add nojeckyll
      - name: Add nojeckyll
        run: touch docs/build/.nojekyll

      # Publish API docs
      - name: Publish API docs
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/build
          SQUASH_HISTORY: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
