# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: "*"
#  pull_request:
#    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "linux"
  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Install dependencies
      # setuptools required by pre-commit
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest pandas vaex sortedcontainers
          python -m pip install git+https://github.com/yohplala/fastparquet@cmidx_write_rg
#          python -m pip install --upgrade pytest poetry
#          python -m pip install --upgrade pip setuptools wheel poetry pre-commit pytest
#          poetry config experimental.new-installer false

      # Setup cached pre-commit
#      - name: Setup cached pre-commit
#        id: cache-pre-commit
#        uses: actions/cache@v2
#        with:
#          path: ~/.cache/pre-commit
#          key: pre-commit-${{ hashFiles('.github/workflows/*.yml', '.pre-commit-config.yaml') }}

      # Run pre-commit
#      - name: Run pre-commit
#        run: pre-commit run --all-files

      # Install oups
#      - name: Install oups
#        run: poetry install

      # Run pytest
      - name: Run pytest
#        run: poetry run pytest
        run: python -m pytest
