name: test

# Test oups.

on:
  push:
    branches: "*"
#  pull_request:
#    branches: main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      # setuptools required by pre-commit
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel pre-commit pytest poetry

      # Setup pre-commit cache
      - name: Setup pre-commit cache
        id: cache-pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.github/workflows/*.yml', '.pre-commit-config.yaml') }}

      # Run pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

      # Setup poetry cache
      - name: Get poetry cache dir
        id: cache-poetry
        run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

      - name: Setup poetry cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-poetry.outputs.dir }}
          key: poetry-${{ hashFiles('.github/workflows/*.yml', '**/pyproject.toml') }}

      # Install oups
      - name: Install oups
        run: poetry install

      # Run pytest
      - name: Run pytest
        run: poetry run pytest
